Seungheonoh/utxo
Liqwid-Labs/plutarch-context-builder pull request #16
Opened 2022-07-22 15:14 UTC by SeungheonOh

2022-07-22 16:59 UTC, peter-mlabs reviewed
I think this all makes sense. Are you happy with the API as is now?

2022-07-22 16:59 UTC, peter-mlabs commented on src/Plutarch/Context/Base.hs
> +withTxId :: TxId -> UTXO
Looking at this type signature and implementation, it just feels like we're hiding a function argument behind the type synonym. 

But I guess the API we're trying to present is `withXYZ` takes an `XYZ` and creates a `UTxO` and then the `UTxO`s can be monoidally combined?

2022-07-22 18:34 UTC, SeungheonOh commented on src/Plutarch/Context/Base.hs
> +type UTXO = (UTXO' -> UTXO')
Ah hmm. I think we should ask @kozross for this. However, I think it's not too bad in this case since we are not dealing with typelevel stuff--like Plutarch.

2022-07-22 18:38 UTC, SeungheonOh commented on src/Plutarch/Context/Base.hs
> +withTxId :: TxId -> UTXO
I considered that when I was building it, but that would give code like following
```hs
mconcat $ 
[ input . mconcat $ 
    [ withValue mempty
    , withXyz abc
    , withAbc xyz
    ]
]
```
And I chose point free composing style to avoid such nested look. But, I do think making `UTXO` a monoid is a good idea.

2022-07-22 18:39 UTC, SeungheonOh commented on src/Plutarch/Context/Base.hs
> +withTxId :: TxId -> UTXO
```hs
mconcat $ 
[ input $ 
    withValue mempty <>
    withXyz abc <>
    withAbc xyz
]
```
actually, this isn't that bad

2022-07-22 18:56 UTC, kozross commented on src/Plutarch/Context/Base.hs
> +type UTXO = (UTXO' -> UTXO')
`type` is _bad_. In every context. It turns error messages into a non-deterministic soup. Either use `newtype` if you need an abstraction boundary, or just spell it.

Worth mentioning here: `Endo Utxo'` is viable in this case. You even get `Semigroup` and `Monoid` for it.

2022-07-22 23:09 UTC, SeungheonOh commented on src/Plutarch/Context/Base.hs
> +type UTXO = (UTXO' -> UTXO')
Ah. Okay. I'll have to get rid of `type`s. Thanks for letting me know `Endo`, that might be a better option. Otherwise, I would need to just ditch current point free interface and use Monoid.

2022-07-25 20:45 UTC, kozross commented on src/Plutarch/Context/Base.hs
> +type UTXO = (UTXO' -> UTXO')
`Monoid` is honestly probably what you want here.

2022-07-25 20:46 UTC, kozross requested changes

2022-07-25 20:46 UTC, kozross commented on src/Plutarch/Context/Base.hs
>   @since 1.1.0
Version bump I think, since I think you expose the constructor, and its signature's changed.

2022-07-26 17:10 UTC, SeungheonOh commented
This can be merged @peter-mlabs @kozross

2022-07-26 18:54 UTC, peter-mlabs commented on src/Plutarch/Context/SubBuilder.hs
> +{- | Builds all TxInInfos from give builder. Returns reason when failed.
given*

2022-07-26 18:55 UTC, peter-mlabs commented
Great, going to merge

2022-07-26 18:55 UTC, merged