Phase-1 Validation
Liqwid-Labs/plutarch-context-builder pull request #17
Opened 2022-07-22 18:41 UTC by SeungheonOh

close #15

2022-07-22 19:03 UTC, peter-mlabs requested changes
I think we should have a check that the mints field matches the difference between inputs and outputs, right?

2022-07-22 19:22 UTC, SeungheonOh commented
```hs
inOutZeroSum :: P1Validator
inOutZeroSum b@(unpack -> BB{..})
    | i <> m <> bbFee == o = Success b
```

zero sum check does it

2022-07-24 19:51 UTC, peter-mlabs commented
Awesome, missed that.

2022-07-24 21:43 UTC, kozross requested changes

2022-07-24 21:43 UTC, kozross commented on src/Plutarch/Context/Minting.hs
> +
Since this is exported, there should be a version bump (minor will do), a `since` annotation, and a changelog entry.

2022-07-24 21:43 UTC, kozross commented on src/Plutarch/Context/Phase1.hs
> +type Checker = forall a. Builder a => a -> Validation [String] a
I _strongly_ do not advise this. Even if you can get GHC to infer this properly (and there's no guarantee you can, look at `ClosedTerm`!), your error messages will be absolute soup. Just write a newtype!

Also, `[String]` is a pretty awful way of reporting errors. It has quadratic semantics (since each `<>` forces a linear traversal) and `String` is _utterly_ useless for recovery, and not much better even for reporting, as we would very likely want to present it some other way. Fixes are as follows:

* Use a better appendy `Monoid` (`Acc` is my preference); and
* Make a sum type indicating the different ways we can fail.

2022-07-24 21:43 UTC, kozross commented on src/Plutarch/Context/Spending.hs
> +
Same as before.

2022-07-25 16:12 UTC, SeungheonOh commented
I removed the type synonym, but now, I don't really like how checker is constructed. Since `Checker` cannot get functor nor contrafunctor, I don't really see a good way of combining them :thinking:

2022-07-25 17:23 UTC, kozross commented
You can make `Checker` a synonym over `a -> Validation (Acc CheckerError) ()`, which is happily `Contravariant`, `Divisible` and `Decidable`. We can do this because `Checker` doesn't return a useful value: this means we can do

```
runChecker :: forall (a :: Type) . Checker a -> a -> Validation (Acc CheckerError a)
runChecker (Checker comp) x = comp x $> x
```

2022-07-25 18:12 UTC, SeungheonOh commented
Can we just make checkers return `Acc CheckerError`? It seems to work fine and we don't have to deal with `Validation`. 

I'll push the update in a moment with this change.

2022-07-25 18:37 UTC, kozross commented
That also works. Still has all the instances too.

2022-08-06 00:41 UTC, peter-mlabs commented
This is superceded by #20, right?

2022-08-06 05:39 UTC, SeungheonOh commented
That's correct.

2022-08-06 05:39 UTC, closed without merging