PlutusLedgerApi.V2 support; Inline Datum, Reference Inputs, and more
Liqwid-Labs/plutarch-context-builder pull request #20
Opened 2022-08-04 19:46 UTC by SeungheonOh

2022-08-06 00:32 UTC, peter-mlabs requested changes
Some changes, mostly needing to add some more doc strings.

`Phase1` is a good start to a complicated problem, but I think it needs some renaming and an overall module doc string indicating that there is a very small subset of the total checks that we want. After this is merged, I wouldn't put too much more effort into this until we've worked something out with Jared.

2022-08-06 00:32 UTC, peter-mlabs commented on src/Plutarch/Context/Base.hs
> +reference x = pack mempty{bbReferenceInputs = pure x}
This name should be more descriptive -- CIP 31 is "reference inputs", CIP 33 is "reference scripts". How does `referenceInput` sound?

2022-08-06 00:32 UTC, peter-mlabs commented on src/Plutarch/Context/Phase1.hs
> +checkByteString = Checker $ \y -> if lengthOfByteString y == 28 then mempty else pure $ IncorrectByteString
Could you explain this one?

2022-08-06 00:32 UTC, peter-mlabs commented on src/Plutarch/Context/Phase1.hs
> +    isPos = all (\(_, _, x) -> x > 0) . flattenValue
This needs a better name and documentation. 

Some notes:

- `Value` can contain negative entries if it's part of a mint (negative entries represent burning tokens)
- `Value` can contain a zero entry if the asset class is `(adaSymbol, adaToken)`, and _must_ contain a zero entry if the value does not contain Ada.

2022-08-06 00:32 UTC, peter-mlabs commented on src/Plutarch/Context/Phase1.hs
> +checkByteString = Checker $ \y -> if lengthOfByteString y == 28 then mempty else pure $ IncorrectByteString
Oh, I see now this is for checking `TxId`s and `PubKeyHash`es. We should add a doc string here.

2022-08-06 00:32 UTC, peter-mlabs commented on src/Plutarch/Context/Phase1.hs
> +{- | Check if input, output, mint have zero sum.
Does the fee need to be included in this too?

2022-08-06 00:32 UTC, peter-mlabs commented on src/Plutarch/Context/Phase1.hs
> +{- | Check if input, output, mint have zero sum.
Oh, I see that its in the implementation. Lets add it to the doc string.

2022-08-08 20:36 UTC, SeungheonOh commented
Some sample of new error messages:
```
    Error at Input:
        Given validator input does not exist in inputs: 
            ValidatorOutRefIdx 10
```
```
    Error at Input:
        Value (Map [(,Map [("",100)]),(cc,Map [("hello",-50)])]) is an invalid value (contains non positive).
    Error at Fee:
        Transaction takes tokens other than Ada as fee: Value (Map [(cc,Map [("non Ada Fee",330)])])
    Error at TxInfo:
        Transaction doesn't not have equal inflow and outflow.
        Diff: Value (Map [(aaaa,Map [("hello",-3)]),(cc,Map [("hello",-100),("non Ada Fee",330)])])
    Error at Signatories:
        Signature not provided
```

2022-08-09 20:46 UTC, kozross requested changes
A few minor things, mostly to do with `since`s and changelog entries.

2022-08-09 20:46 UTC, kozross commented on sample/Main.hs
> +{-# OPTIONS_GHC -Wno-unused-imports #-}
This shouldn't be here.

2022-08-09 20:46 UTC, kozross commented on src/Plutarch/Context/Base.hs
> +    a
Kind signature.

2022-08-09 20:46 UTC, kozross commented on src/Plutarch/Context/SubBuilder.hs
> +    deriving newtype (Semigroup, Monoid)
Not a problem per se, but I prefer `deriving via` even for newtypes. I've been bitten several times by changes in underlying representation silently changing instance behaviour without the compiler reminding me.

2022-08-09 20:46 UTC, kozross commented on src/Plutarch/Context/SubBuilder.hs
> +    fst $ yieldInInfoDatums bbInputs
Changes in signature require a change in their `since`

2022-08-10 14:39 UTC, peter-mlabs commented
I think this can be g2g once the failing test is fixed.

2022-08-10 14:44 UTC, SeungheonOh commented
Ah okay, I thought I fixed it already. I'll fix it really quick.

2022-08-10 15:16 UTC, merged