Add interfaces for `StakingCredential`
Liqwid-Labs/plutarch-context-builder pull request #22
Opened 2022-08-22 18:38 UTC by SeungheonOh

2022-08-22 19:16 UTC, kozross requested changes
Version bump, `since`s, etc.

2022-08-23 01:11 UTC, peter-mlabs approved these changes
Fixed a typo. We can merge once CI passes

2022-08-23 01:11 UTC, peter-mlabs commented on src/Plutarch/Context/Base.hs
> +{- | Specify value of a UTXO. This will me monoidally merged values
'be', not 'me'.

2022-08-23 01:29 UTC, SeungheonOh commented on src/Plutarch/Context/Base.hs
> +{- | Specify value of a UTXO. This will me monoidally merged values
Thank you!

2022-08-23 01:41 UTC, kozross approved these changes

2022-08-23 02:06 UTC, merged