Redeemer Map Support
Liqwid-Labs/plutarch-context-builder pull request #28
Opened 2022-09-02 05:00 UTC by chfanghr

2022-09-02 13:52 UTC, chfanghr commented
Sure, dropped the second commit :)

2022-09-02 14:50 UTC, SeungheonOh commented
Thank you!

2022-09-02 15:03 UTC, SeungheonOh commented on src/Plutarch/Context/Base.hs
> +yieldScriptInputRedeemerMap ::
`yieldScriptInputRedeemerMap` and `yieldMapInputRedeemerMap` can be combined as each `yield*` accounts for each fields in `TxInfo`

2022-09-02 15:11 UTC, chfanghr commented on src/Plutarch/Context/Base.hs
> +yieldScriptInputRedeemerMap ::
Well, my initial intention was to ensure that no `TxOutRef` has been spent twice, by checking the result of `yieldScriptInputRedeemerMap`. And then I realized that I don't have to do it at all, cause we have already ensured no UTxO with duplicate `TxOutRef`. So yeah, you're right, I will combine these two.

2022-09-02 15:19 UTC, SeungheonOh requested changes
Thank you. I see it's not fully done, especially on each builders, but here's some comments.

2022-09-02 15:19 UTC, SeungheonOh commented on src/Plutarch/Context/Base.hs
> +    { mintSymbol :: CurrencySymbol
I think `mintValue` is better. We can enforce it to only have single `CurrencySymbol` on the `mint` and `mintWith` interfaces.

2022-09-02 15:19 UTC, SeungheonOh commented on src/Plutarch/Context/Base.hs
> +-- | @since 2.3.0
Some docstring would be nice.

2022-09-02 15:19 UTC, SeungheonOh commented on src/Plutarch/Context/Base.hs
> +-- | @since 2.3.0
Honestly, we can just use `(Value, Maybe Data)` on `BaseBuilder` because there's no monoidal action we want for `Mint`.

2022-09-02 15:19 UTC, SeungheonOh commented on src/Plutarch/Context/Check.hs
> +  where
This is fine, but it'd be nice to put this in contravariant style(with `contramap`) if possible.

It will start like:
```hs
contramap ((fromMaybe (PubKeyCredential "") . utxoCredential) &&& utxoRedeemer)) (... :: Checker e (Credential, Redeemer)) 
```

2022-09-02 15:21 UTC, SeungheonOh commented on src/Plutarch/Context/Base.hs
> +yieldScriptInputRedeemerMap ::
Right, duplication of inputs are taken care of by `yieldInInfoDatum`.

2022-09-02 15:22 UTC, SeungheonOh commented on src/Plutarch/Context/Base.hs
> +yieldScriptInputRedeemerMap ::
Also, if my understanding is correct, not all `UTXO` have `Redeemer` attached. Am I correct?

2022-09-02 15:29 UTC, chfanghr commented on src/Plutarch/Context/Check.hs
> +  where
I was unable to get my head around CPS lol ... will do

2022-09-05 04:26 UTC, chfanghr commented on src/Plutarch/Context/Base.hs
> +yieldScriptInputRedeemerMap ::
Yep, only inputs from validators should have one. afaik.

2022-09-06 15:18 UTC, SeungheonOh requested changes
Thank you!

2022-09-06 15:18 UTC, SeungheonOh commented on src/Plutarch/Context/Base.hs
> +    utxoToRedeemerPair u = do
type signatures on `where` functions.

2022-09-06 15:18 UTC, SeungheonOh commented on src/Plutarch/Context/Base.hs
> +{- | Associate a redeemer to a UTXO.
Need to state that it will add redeemer if and only if both `TxId` and `TxIdx` for output reference is given

2022-09-06 15:18 UTC, SeungheonOh commented on src/Plutarch/Context/Base.hs
> +mintWith ::
I think `mintWith` should take `Value` and redeemer

2022-09-06 15:18 UTC, SeungheonOh commented on src/Plutarch/Context/Base.hs
> +    valueToMints :: Value -> [Mint]
we have `flattenValue` function in `Checker` module. This is fine but it'd be nice to isolate `AssocMap` as much as possible as they are ~~horrible~~

2022-09-06 15:18 UTC, SeungheonOh commented on src/Plutarch/Context/Base.hs
> +data Mint = Mint
I thought more about this. I think we really should have `Value` with a new checker that checks if minted `Value` have multiple currency symbol or not. 

We have different things on PCB bulider that is quite illegal and it's there because we want to give freedom that is enough to make a malformed contexts. For example, PCB builders allow you to build with an illegal TxIds or empty pubkeyhash and etc.  Here, I think having ability to make a context that mints in multiple CS is actually what we need.

Having mint limited to one currency symbol would be quite restricting, and we want more freedom on builder itself. That's what we struggled before because builders and checkers were same thing, until we make builder build whatever we throw them and checker check them on request. It will be a nightmare to maintain if we had a giant builder that both builds and checks :D

If users don't want an illegal context, subsequent checker will "warn" user not to have context minting in multiple currency symbols, but builder will **_always_** build something for the user. 

For now, you can just make it `Value`. I'll add `Checker` later if you prefer.

2022-09-07 11:34 UTC, chfanghr commented on src/Plutarch/Context/Base.hs
> +data Mint = Mint
> Having mint limited to one currency symbol would be quite restricting

The current design doesn't stop you from minting any number of currency symbols. In fact, you can even construct an invalid `txInfoMint` field, by for example, "minting" the same currency twice with different redeemers and opposite amounts. To be clear, we can only represent a "one currency symbol, one redeemer" relationship in the final redeemer map. The problem is, what the semantics of mint APIs will be if we allow this?

2022-09-07 11:38 UTC, chfanghr commented on src/Plutarch/Context/Base.hs
> +data Mint = Mint
If we want the ability to mint an arbitrary value with one redeemer, it might be a good idea to provide another API, which associates the currency symbols with the same redeemer in the redeemer map.

2022-09-07 11:49 UTC, chfanghr commented on src/Plutarch/Context/Base.hs
> +    valueToMints :: Value -> [Mint]
`flattenValue` doesn't do what I want here, unfortunately. Also importing `flattenValue` in the `Base` module will result in a cyclic reference.

2022-09-07 12:35 UTC, SeungheonOh reviewed
I think `Mint` is good. Please address some namming change about `mintWith` and it'd be also nice to have `extraRedeemer` that allows users to add arbitrary redeemer(this will cause illegal context like `extraData`)

Besides, @kozross and @peter-mlabs do you have any strong objection towards the introduction of `Mint` type?

2022-09-07 12:35 UTC, SeungheonOh commented on src/Plutarch/Context/Base.hs
> +data Mint = Mint
Ah, okay. I can see the API getting a bit confusing if we take the `Value` route. I'm convinced that Mint type is a good middle ground between terse API and a freedom of generating contexts.

2022-09-09 02:54 UTC, SeungheonOh commented
I'll merge this once I hear okay from Koz or Peter :+1: Thank you!

2022-09-09 18:59 UTC, peter-mlabs requested changes
This looks mostly good, and I think the `Mint` type is reasonable. 

Can we:

- Fix some of the line length issues
- Add a brief unit test of this feature to track regressions?

2022-09-09 18:59 UTC, peter-mlabs commented on src/Plutarch/Context/Base.hs
> +        UTXO (choose c c') (choose stc stc') (v <> v') (choose d d') (choose rs rs') (choose t t') (choose tidx tidx') (choose r r')
Can we limit line length here?

2022-09-09 18:59 UTC, peter-mlabs commented on src/Plutarch/Context/Base.hs
> -    BB ins refIns outs sigs dats ms fval range tid <> BB ins' refIns' outs' sigs' dats' ms' fval' range' tid' =
Limit line length

2022-09-11 19:18 UTC, kozross requested changes

2022-09-11 19:18 UTC, kozross commented on CHANGELOG.md
> +## 2.3.0 -- 2020-09-08
Bump up the date before merging.

2022-09-13 11:47 UTC, SeungheonOh approved these changes
LGTM.

2022-09-13 12:12 UTC, SeungheonOh approved these changes
GH, please let me merge this...

2022-09-13 12:13 UTC, SeungheonOh approved these changes

2022-09-13 12:16 UTC, merged