Normalizers
Liqwid-Labs/plutarch-context-builder pull request #30
Opened 2022-09-14 22:53 UTC by SeungheonOh

2022-09-14 22:57 UTC, kozross requested changes

2022-09-14 22:57 UTC, kozross commented on src/Plutarch/Context/Base.hs
> +normalizeMint :: Mint -> Mint
`since` and Haddock.

2022-09-14 22:57 UTC, kozross commented on src/Plutarch/Context/Base.hs
> +normalizeUTXO :: UTXO -> UTXO
Same.

2022-09-14 22:57 UTC, kozross commented on src/Plutarch/Context/Base.hs
> +     is equal, using given concat function. The output will be reverse of what's
'the given'
'will be the reverse'

2022-09-14 22:57 UTC, kozross commented on src/Plutarch/Context/Base.hs
> +{- | Given an AssocMap, combine all values when key is equal, using given
"'AssocMap'"
'when the key is equal'
'use the given'

2022-09-14 22:57 UTC, kozross commented on src/Plutarch/Context/Base.hs
> +     concat function. The output will be reverse of what's given.
'be the reverse'

2022-09-14 22:57 UTC, kozross commented on src/Plutarch/Context/Base.hs
> +{- | Sort given AssocMap by given comparator.
"'AssocMap'"

2022-09-14 22:57 UTC, kozross commented on src/Plutarch/Context/Base.hs
> +     'CurrencySymbol' and 'TokenName'.
I assume you mean "by both 'CurrencySymbol' and 'TokenName'" here?

2022-09-14 22:57 UTC, kozross commented on src/Plutarch/Context/Base.hs
> +{- | Normalize and sort Value. It will normalize and sort both
"'Value'"

2022-09-14 22:57 UTC, kozross commented on src/Plutarch/Context/Base.hs
> +  AssocMap.Map k v ->
We don't have a clash with `Map`, so the type should be an unqualified import by the standards.

2022-09-14 23:05 UTC, SeungheonOh commented on src/Plutarch/Context/Base.hs
> +     'CurrencySymbol' and 'TokenName'.
This sounds pretty confusion. I'll just remove the second sentence.

2022-09-14 23:09 UTC, kozross requested changes
New version number in Cabal file.

2022-09-14 23:11 UTC, kozross approved these changes

2022-09-14 23:13 UTC, SeungheonOh commented
Perhaps I should add checker for sortedness. Is this a good idea?

2022-09-14 23:37 UTC, kozross commented
@SeungheonOh it can't hurt, especially now that we have `pisSorted` and `pisSortedBy` to assist you.

2022-09-15 00:23 UTC, kozross requested changes

2022-09-15 00:23 UTC, kozross commented on src/Plutarch/Context/Base.hs
> +  deriving stock (Show, Eq)
`since`s on these, especially since `Eq` is new in this version.

2022-09-15 12:04 UTC, peter-mlabs commented
> Just curious, how would one use this to ensure they don't get bitten by the "PValue map is unsorted" bug? Does the user have to call `mkNormalized` prior to e.g. `buildSpending`? I ask because I wonder if normalization should be the default behavior, where the user can opt-out somehow if they wish.

I agree here -- I think normalization should be the default behavior. I can't thing of an instance where someone would purposefully _want_ a non-normalized value for the sort of testing PCB targets.

2022-09-15 12:54 UTC, chfanghr commented on src/Plutarch/Context/Base.hs
> +        sortBy (\(t, _) (t', _) -> compare t t') $
I suppose we should also ensure that it has a 0 ADA entry.

2022-09-15 12:56 UTC, peter-mlabs commented on src/Plutarch/Context/Base.hs
> +        sortBy (\(t, _) (t', _) -> compare t t') $
Yeah, this is also important.

I'll be doing a more thorough review later today

2022-09-17 05:34 UTC, SeungheonOh commented
I had to add `Normalizer` class to ensure all builder-specific values get normalized. Yet again, this is law-less typeclass, and it is not exported to users. Still, I wounder if there's anyway we can prevent this typeclass.

I thought about using Optics, but even with optics, I don't think it's possible to make a function that does similar thing here. Any suggestions?

2022-09-19 16:31 UTC, peter-mlabs commented
> Yet again, this is law-less typeclass, and it is not exported to users.

I wouldn't call this lawless; the law is that "the implementation must normalize".

2022-09-19 16:33 UTC, peter-mlabs requested changes
Some of this might be a little clunky, but it will be good enough for now once the issues are addressed. Don't worry about cleaning it up more (with respect to the typeclass) at this time.

2022-09-19 16:33 UTC, peter-mlabs commented on src/Plutarch/Context/Base.hs
> +{- | Normalize and sort 'Value'.
You can also see [here](https://github.com/input-output-hk/plutus/blob/a56c96598b4b25c9e28215214d25189331087244/plutus-ledger-api/src/Plutus/V1/Ledger/Value.hs#L174-L188) to understand why the `Show` instance is unreliable, and also where it falls short.

2022-09-19 16:33 UTC, peter-mlabs commented on src/Plutarch/Context/Check.hs
> +    isNormalized val = getValue (normalizeValue val) == getValue val
Glad you caught this and are checking equality on the underlying Map; the `Eq` implementation doesn't behave the way we need. 

If you haven't looked at it in detail yet, the instance uses [`checkBinRel`](https://github.com/input-output-hk/plutus/blob/70834670fe051a98c1d6e78e2d3c772ef1141f8d/plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs#L312), which means that 

```hs
Value $ fromList [(adaSymbol, fromList [(adaToken, 0)])] == Value $ fromList []
```
is true, because both are seen as "zero".

2022-09-19 18:35 UTC, SeungheonOh commented on src/Plutarch/Context/Base.hs
> +{- | Normalize and sort 'Value'.
Thanks for the list!

2022-09-19 19:40 UTC, SeungheonOh commented
`Mint` doesn't allow any other currency symbol. so, we can add `singleton adaSymbol adaToken` when constructing value from `Mint` and it will always be valid.

2022-09-20 13:09 UTC, merged

2022-09-20 13:09 UTC, peter-mlabs commented
Going to merge this now, thanks Seungheon!