fix checker for `TxId`
Liqwid-Labs/plutarch-context-builder pull request #32
Opened 2022-09-26 23:38 UTC by SeungheonOh

Ledger spec changed. It now uses 32 bytes long ByteString

close #31

2022-09-26 23:54 UTC, kozross requested changes
Major bump: this is a breaking change due to the removal of a function.

2022-09-27 00:28 UTC, kozross approved these changes

2022-09-27 01:48 UTC, peter-mlabs requested changes
Small typo, but good once that's fixed

2022-09-27 01:48 UTC, peter-mlabs commented on CHANGELOG.md
> +  at given lengt.h
typo here

2022-09-27 13:37 UTC, peter-mlabs approved these changes

2022-09-27 13:37 UTC, merged