made `buildTxInInfo` consistent with rest of API
Liqwid-Labs/plutarch-context-builder pull request #44
Opened 2022-11-21 20:25 UTC by SeungheonOh

closes #43

2022-11-21 20:28 UTC, kozross requested changes

2022-11-21 20:28 UTC, kozross commented on src/Plutarch/Context/SubBuilder.hs
> +   in TxInInfo (TxOutRef txid txidx) (utxoToTxOut u)
I think we need to document what this default is.

2022-11-21 20:32 UTC, cjay approved these changes

2022-11-21 23:38 UTC, kozross requested changes

2022-11-21 23:38 UTC, kozross commented on src/Plutarch/Context/SubBuilder.hs
> +     a default value("" and 0, respectfully) to create the 'TxInInfo'.
Space after 'value', and 'respectively'.

2022-11-22 00:07 UTC, kozross approved these changes

2022-11-22 00:07 UTC, merged