Rewrite
Liqwid-Labs/plutarch-context-builder pull request #5
Opened 2022-06-07 13:41 UTC by SeungheonOh

![image](https://user-images.githubusercontent.com/24271442/178399499-75aba990-b0bf-48a4-9050-424ce3cc94a8.png)
Nice demo, written by Connor for Agora.

- Base builder APIs are shared across the specific builders
- Allows one to set TxInInfo Idx and Id
- New API styles
- Spending Builder allows one to set what TxInfo to reference
- TxInfo Builder
- Other changes as well.

2022-07-14 20:58 UTC, peter-mlabs requested changes
I'm going to leave some general comments here on files outside of this PR, since this is a rewrite anyways.

---------

We should get rid of `yieldExtraDatums`. This isn't actually possible onchain, to my knowledge, and is a mythology that's struck almost everyone. If you want a datum, we should require that it's included with an input or output.

------

Perhaps not for this PR, but we should perform basic phase 1 validation. This includes:

- Normalizing `Value`s
- Sorting transaction inputs
- Sorting the datum map
- [Sorting the signatories](https://discordapp.com/channels/922576618424250418/922577570766143498/997119045323206656)
- De-duplicating the above

----

Otherwise, this looks good! Excited to use it

2022-07-17 23:50 UTC, kozross requested changes

2022-07-17 23:50 UTC, kozross commented on src/Plutarch/Context.hs
> +import Plutarch.Context.TxInfo
I am not a fan of this style of re-export. It is hard to maintain, hard to see where anything is coming from, and ruins Haddocks. If we _really_ want full module dumps, then they should just be rolled in; if not, then qualified imports and a proper export list is the way.

2022-07-17 23:50 UTC, kozross commented on src/Plutarch/Context/Base.hs
> + License: Proprietary
I don't think this is true anymore - isn't PCB public?

2022-07-17 23:50 UTC, kozross commented on src/Plutarch/Context/Base.hs
> + @unpack@ will sometimes loose data.
'lose'.

2022-07-17 23:50 UTC, kozross commented on src/Plutarch/Context/Base.hs
> + Typeclass Rules:
We usually call these 'laws'.

2022-07-17 23:50 UTC, kozross commented on src/Plutarch/Context/Base.hs
> +    unpack :: a -> BaseBuilder
The `Monoid` superclass constraint here is a bit odd. Neither the operations nor the laws rely on anything about `a` being monoidal.

Furthermore, why a type class? Admittedly it _is_ law-abiding, but what seems to be going on here is that you have a lens: you can retrieve a `BaseBuilder`, and modify one that's 'nested' inside an `a`. Surely that would have been enough to get the desired generality?

2022-07-17 23:50 UTC, kozross commented on src/Plutarch/Context/Base.hs
> +            | otherwise = b
Are we confident `choose` gives us the associativity we expect? I'm not sure it does.

2022-07-17 23:50 UTC, kozross commented on src/Plutarch/Context/Base.hs
> +    (Builder b) => b -> ContT a (Either String) TxInfo
I _really_ want to know what about this problem warrants the use of _delconts_.

2022-07-17 23:50 UTC, kozross commented on src/Plutarch/Context/TxInfo.hs
> +{-# LANGUAGE ViewPatterns #-}
This module is wholesale re-exported without _any_ Haddocks.

2022-07-17 23:50 UTC, kozross commented on test/BaseBuilder.hs
> +toUTXO :: [UTXOComponents] -> (UTXO -> UTXO)
Is there a reason why this has to return a _function_? Technically I understand that `a -> b -> c` is in fact `a -> (b -> c)`, but it's a bit odd to see.

2022-07-17 23:50 UTC, kozross commented on test/BaseBuilder.hs
> +instance Arbitrary BuilderInterface where
This needs a shrinker _very_ badly; without one, we run the risk of totally unreadable counter-examples.

2022-07-18 14:44 UTC, SeungheonOh commented on src/Plutarch/Context/Base.hs
> +    unpack :: a -> BaseBuilder
`Monoid` is there because all builders *should* be a `Monoid`. For instance, 
```hs
test :: Builder a => a
test =
    mconcat
        [ input $
            pubKey "aabb"
                . withValue (singleton "cc" "hello" 123)
                . withRefIndex 5
        ]
```
Once can have a "common" part of Context like so and add specific part on top. If you don't have `Monoid` constraint, Nothing can be used across different builders. I don't think Optics as well can do this quite as smoothly what we currently have.

2022-07-18 14:49 UTC, SeungheonOh commented on src/Plutarch/Context/Base.hs
> +            | otherwise = b
I'm pretty sure it does give associativity. `choose` simply takes what comes right when the right is not empty.

2022-07-18 15:11 UTC, SeungheonOh commented on src/Plutarch/Context/Base.hs
> +            | otherwise = b
```hs
import Test.QuickCheck

data A = A Integer deriving (Eq, Show)

instance Semigroup A where
	(<>) (A a) (A b)
	    | b == 0 = A a
 	    | otherwise = A b

instance Monoid A where
    mempty = A 0

instance Arbitrary A where
    arbitrary = A <$> arbitrary 

assoc :: Property
assoc = property test
    where
      test :: A -> A -> A -> Property
      test a b c = (a <> b) <> c === a <> (b <> c)
```

2022-07-18 15:13 UTC, SeungheonOh commented on test/BaseBuilder.hs
> +toUTXO :: [UTXOComponents] -> (UTXO -> UTXO)
This tests are obsolete. Need a rewrite

2022-07-18 15:21 UTC, SeungheonOh commented on src/Plutarch/Context.hs
> +import Plutarch.Context.TxInfo
I'd require users to import multiple things: they'd need base and other module they are building. I don't think these modules are different enough to be exported separately.  

Qualified imports should be a better method I think, since we don't want to expose some internal functions.

2022-07-18 19:16 UTC, kozross commented on src/Plutarch/Context/Base.hs
> +    unpack :: a -> BaseBuilder
We can just constrain functions as `(Monoid b, Builder b)` instead of stitching in a superclass constraint. Arguably, this is 'too strong', and we can probably avoid having a `Monoid` requirement this high up. As a general rule, if you don't need a superclass constraint to state a law or define functionality, it doesn't need to be there.

2022-07-18 19:17 UTC, kozross commented on src/Plutarch/Context/Base.hs
> +            | otherwise = b
OK, if that passes, I'm convinced.

2022-07-18 19:17 UTC, kozross commented on src/Plutarch/Context/Base.hs
> +    (Builder b) => b -> ContT a (Either String) TxInfo
Delimited continuations - this is what `ContT` gives us.

2022-07-18 20:12 UTC, SeungheonOh commented on src/Plutarch/Context/Base.hs
> +    unpack :: a -> BaseBuilder
That make sense; I'm convinced that it should go.

2022-08-10 15:25 UTC, SeungheonOh commented
Anything preventing us from merging this to main?

2022-08-10 16:10 UTC, peter-mlabs commented
Just the conflicts

2022-08-10 17:16 UTC, SeungheonOh commented
Good to go.

2022-08-11 15:36 UTC, merged